### PR TITLE
Important changes for readability. That will help you on your Journey.

### PR DESCRIPTION
**Pull request by MichaelDimmitt**

### CODE REVIEW

**Comment by MichaelDimmitt** [comment]
@TylerGlisson, any chance we can get this merged? 😇

**Review by TylerGlisson — APPROVED** [review]
Thank you for the updates.

**Comment by TylerGlisson** [comment]
Thanks Dimmitt!  Merge commencing

**Comment by MichaelDimmitt** [comment]
@tylerglisson let me know if you have any questions regarding react. Also check your email for the slack invite. 

Looking forward to seeing what direction you take the project. Interested in seeing what you can create with this starting point.

**Pull request merged**
